const puppeteer = require('puppeteer');
const { cloudinary } = require('../config/cloudinary');

class PdfService {
  async generateAndUploadPDF(htmlContent, filename) {
    const browser = await puppeteer.launch({ 
      args: ['--no-sandbox', '--disable-setuid-sandbox'] 
    });
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    const pdfBuffer = await page.pdf({ 
      format: 'A4',
      printBackground: true,
      margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
    });
    await browser.close();

    return new Promise((resolve, reject) => {
      const uploadStream = cloudinary.uploader.upload_stream(
        { resource_type: 'raw', folder: 'vyaparsetu_pdfs', public_id: filename + '_' + Date.now() },
        (error, result) => {
          if (error) return reject(error);
          resolve(result.secure_url);
        }
      );
      uploadStream.end(pdfBuffer);
    });
  }

  async generatePO(po) {
    const html = `
      <div style="font-family: Arial, sans-serif; padding: 40px; color: #333;">
        <h1 style="color: #1a73e8; border-bottom: 2px solid #1a73e8;">VyaparSetu - PURCHASE ORDER</h1>
        <div style="display: flex; justify-content: space-between; margin-top: 20px;">
          <div>
            <strong>PO Number:</strong> ${po.poNumber}<br>
            <strong>Date:</strong> ${new Date().toLocaleDateString()}
          </div>
        </div>
        <div style="margin-top: 40px;">
          <p><strong>Total Amount:</strong> $${po.totalAmount}</p>
        </div>
        <div style="margin-top: 100px; border-top: 1px solid #ccc; padding-top: 10px;">
          <p style="font-size: 10px; color: #666;">Generated by VyaparSetu ERP System</p>
        </div>
      </div>
    `;
    return await this.generateAndUploadPDF(html, 'po_' + po.poNumber);
  }

  async generateInvoice(invoice) {
    const itemsHtml = invoice.items.map(item => `
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #eee;">${item.itemDescription}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: center;">${item.quantity}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right;">$${item.unitPrice}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right;">$${item.amount}</td>
      </tr>
    `).join('');

    const html = `
      <html>
      <head>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; }
          .header { display: flex; justify-content: space-between; border-bottom: 4px solid #28a745; padding-bottom: 20px; }
          .brand { color: #28a745; font-size: 32px; font-weight: bold; }
          .invoice-info { text-align: right; }
          .details { display: flex; justify-content: space-between; margin: 40px 0; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { background: #f8f9fa; padding: 12px; text-align: left; border-bottom: 2px solid #dee2e6; }
          .totals { margin-top: 30px; text-align: right; }
          .status-badge { display: inline-block; padding: 5px 15px; border-radius: 20px; background: #fff3cd; color: #856404; font-size: 12px; font-weight: bold; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="brand">VyaparSetu</div>
          <div class="invoice-info">
            <h2 style="margin: 0; color: #666;">${invoice.invoiceType} INVOICE</h2>
            <p style="margin: 5px 0;"><strong>#${invoice.invoiceNumber}</strong></p>
            <div class="status-badge">${invoice.status}</div>
          </div>
        </div>

        <div class="details">
          <div>
            <h4 style="color: #666; margin-bottom: 10px;">FROM</h4>
            <strong>${invoice.vendor ? invoice.vendor.companyName : 'N/A'}</strong><br>
            ${invoice.vendor ? invoice.vendor.address || '' : ''}<br>
            Email: ${invoice.vendor ? invoice.vendor.contactEmail : ''}
          </div>
          <div style="text-align: right;">
            <h4 style="color: #666; margin-bottom: 10px;">DATE</h4>
            Date: ${new Date(invoice.invoiceDate).toLocaleDateString()}<br>
            Due: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : 'N/A'}
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th style="text-align: center;">Qty</th>
              <th style="text-align: right;">Price</th>
              <th style="text-align: right;">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHtml}
          </tbody>
        </table>

        <div class="totals">
          <p>Subtotal: <strong>$${invoice.subtotal}</strong></p>
          <p>Tax: <strong>$${invoice.taxAmount}</strong></p>
          <p>Discount: <strong>-$${invoice.discountAmount}</strong></p>
          <h2 style="color: #28a745;">Grand Total: $${invoice.grandTotal}</h2>
        </div>

        <div style="margin-top: 60px;">
          <p><strong>Payment Terms:</strong> ${invoice.paymentTerms || 'N/A'}</p>
          <p><strong>Remarks:</strong> ${invoice.remarks || 'N/A'}</p>
        </div>

        <div style="margin-top: 60px; display: flex; justify-content: space-between;">
          <div style="width: 250px; border-top: 1px solid #333; padding-top: 10px; text-align: center;">
            Authorized Signatory
          </div>
          <div style="font-size: 10px; color: #999; text-align: right;">
            Generated on ${new Date().toLocaleString()}
          </div>
        </div>
      </body>
      </html>
    `;
    return await this.generateAndUploadPDF(html, 'invoice_' + invoice.invoiceNumber);
  }
}

module.exports = new PdfService();
